# Permalinks
permalink:           pretty

# Setup
title:               Atnimak`s journey
tagline:             From little boy to java developer
paginate:         10
paginate_path:    "page:num"
highlighter:      rouge
future:           false
show_drafts:      false

url:                 atnimak.github.io
baseurl:             ""

# Assets
#
# We specify the directory for Jekyll so we can use @imports.
sass:
  sass_dir:          _sass
  style:            :compressed

# About/contact
author:
  name:              Antonov Maxim
  url:               https://github.com/atnimak
  email:             atnimak@gmail.com

# This is the list of pages to include in the header of the website.
pages_list:
  О блоге: '/about'
  Архив записей: '/archive'
  Теги: '/tags'
  Лента: '/atom.xml'
  Резюме: '/resume'


# Custom vars
version:             2.0.0
github:
  repo:              https://github.com/poole/poole

# Gems
gems:
  - jemoji
  - jekyll-paginate
  - jekyll-gist
